/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Detail: typeof import('./src/components/Detail.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Item: typeof import('./src/components/Item.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/Theme.vue')['default']
  }
}
